# Generated by Django 3.1.4 on 2020-12-22 17:03

import colorfield.fields
from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=50)),
                ('clicks', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ServiceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(default='', max_length=100)),
                ('prefix', models.CharField(max_length=100)),
                ('image', models.ImageField(default='/static/referralroulette/missing.png', upload_to='images')),
                ('color', colorfield.fields.ColorField(default='#F5F5F5', max_length=18)),
                ('text_color', colorfield.fields.ColorField(default='#212529', max_length=18)),
                ('clicks', models.IntegerField()),
                ('active', models.BooleanField()),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
    ]
