# Generated by Django 3.1.4 on 2021-01-13 21:26

import colorfield.fields
from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('slug', models.SlugField(unique=True)),
                ('color', colorfield.fields.ColorField(default='#212529', max_length=18)),
                ('image', models.ImageField(default='/category_images/missing.png', upload_to='category_images')),
            ],
        ),
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_email', models.EmailField(max_length=254)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='ReferralModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=30)),
                ('slug', models.SlugField()),
                ('link', models.CharField(max_length=100, unique=True)),
                ('email', models.CharField(max_length=50)),
                ('clicks', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.CharField(default='', max_length=100)),
                ('company_description', models.CharField(default='', max_length=3000)),
                ('referral_description', models.CharField(default='', max_length=3000)),
                ('prefix', models.CharField(max_length=100)),
                ('default_link', models.CharField(default='', max_length=100)),
                ('image', models.ImageField(default='/service_images/missing.png', upload_to='service_images')),
                ('background_color', colorfield.fields.ColorField(default='#F5F5F5', max_length=18)),
                ('text_color', colorfield.fields.ColorField(default='#212529', max_length=18)),
                ('clicks', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
    ]
