# Generated by Django 3.1.4 on 2020-12-22 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referralroulette', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicemodel',
            name='image',
            field=models.ImageField(default='/static/referralroulette/missing.png', upload_to='service_images'),
        ),
    ]
