# Generated by Django 3.1.4 on 2021-01-21 03:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('referralroulette', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicemodel',
            name='active',
        ),
        migrations.AddField(
            model_name='servicemodel',
            name='code',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
