# Generated by Django 3.1.4 on 2021-01-21 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referralroulette', '0002_auto_20210121_0352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicemodel',
            name='prefix',
            field=models.CharField(default='', max_length=100),
        ),
    ]
