# Generated by Django 3.1.4 on 2020-12-23 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referralroulette', '0002_auto_20201222_2302'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicemodel',
            old_name='color',
            new_name='background_color',
        ),
        migrations.AlterField(
            model_name='servicemodel',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='servicemodel',
            name='clicks',
            field=models.IntegerField(default=0),
        ),
    ]
