# Generated by Django 3.1.4 on 2021-01-21 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referralroulette', '0003_auto_20210121_0645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicemodel',
            name='default_link',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='servicemodel',
            name='description',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='servicemodel',
            name='prefix',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
