# Generated by Django 3.1.4 on 2020-12-23 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referralroulette', '0003_auto_20201223_0235'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicemodel',
            name='display_name',
            field=models.CharField(default='amazon', max_length=30),
            preserve_default=False,
        ),
    ]
