# Generated by Django 3.1.4 on 2020-12-23 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referralroulette', '0004_servicemodel_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicemodel',
            name='image',
            field=models.ImageField(default='/static/missing.png', upload_to='service_images'),
        ),
    ]
