# Generated by Django 3.1.4 on 2020-12-23 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referralroulette', '0005_auto_20201223_0306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicemodel',
            name='display_name',
        ),
        migrations.AddField(
            model_name='servicemodel',
            name='slug',
            field=models.SlugField(default='', unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='servicemodel',
            name='image',
            field=models.ImageField(default='/service_images/missing.png', upload_to='service_images'),
        ),
    ]
