# Generated by Django 3.1.4 on 2020-12-30 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referralroulette', '0007_referralmodel_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(default='/category_images/missing.png', upload_to='category_images')),
            ],
        ),
        migrations.AlterField(
            model_name='referralmodel',
            name='clicks',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='referralmodel',
            name='link',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
