# Generated by Django 3.1.4 on 2020-12-30 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referralroulette', '0008_auto_20201230_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='referralmodel',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
