# Generated by Django 3.1.4 on 2020-12-31 18:30

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('referralroulette', '0009_referralmodel_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorymodel',
            name='color',
            field=colorfield.fields.ColorField(default='#212529', max_length=18),
        ),
    ]
