# Generated by Django 3.1.4 on 2021-01-10 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referralroulette', '0010_categorymodel_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicemodel',
            name='company_description',
            field=models.CharField(default='', max_length=3000),
        ),
        migrations.AddField(
            model_name='servicemodel',
            name='referral_description',
            field=models.CharField(default='', max_length=3000),
        ),
    ]
