# Generated by Django 3.1.4 on 2021-01-10 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referralroulette', '0011_auto_20210110_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicemodel',
            name='default_link',
            field=models.CharField(default='', max_length=100),
        ),
    ]
